apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: devops
spec: {}
status: {}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-proxy
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
    verbs:
      - get
      - create

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-proxy
  namespace: mgmt

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-proxy-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-proxy
subjects:
  - kind: ServiceAccount
    name: node-proxy
    namespace: mgmt

---

apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: node-proxy-sat
  namespace: mgmt
  annotations:
    kubernetes.io/service-account.name: "node-proxy"
