apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: mgmt
spec: {}
status: {}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: security-reader
  namespace: mgmt
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: security-reader
  namespace: mgmt

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: security-reader-rb
  namespace: mgmt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: security-reader
subjects:
- kind: ServiceAccount
  name: security-reader
  namespace: mgmt
