header: 
  license:
    spdx-id: GPL-3.0-or-later
    copyright-owner: Specter Ops, Inc.
    software-name: AzureHound
  paths:
  - 'main.go'
  paths-ignore:
    - .git
    - dist
    - licenses
    - '**/*.md'

  comment: on-failure

  dependency:
    files:
      - go.mod
