name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -upgrade
      - name: Terraform Format Check
        working-directory: terraform
        run: terraform fmt -check -recursive
      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

  python-lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Linters
        run: pip install flake8 pyflakes
      - name: Lint Agent Code
        run: |
          flake8 inspiration-tools
          pyflakes inspiration-tools/agent.py

  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Agent Docker Image
        run: |
          docker build -f Dockerfile.agent -t security-agent:latest .